name: Publish Web Naren

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_PROD_ID }}

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [ui-changed-naren]
  workflow_dispatch:

jobs:

  publish-web-naren-netlify:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out lite
      - name: Checkout lite
        uses: actions/checkout@v4
        with:
          repository: statstrade-dev/statstrade-v1
          branch: naren
          path: src-js/sznui
          token: ${{ secrets.GH_TOKEN }} # Personal Access Token with repo write access
          
      - name: Show full commit SHA
        run: git rev-parse HEAD

      # 2. Install Node and Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Check Node version
        run: node -v

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Copy .env.local from projects/web/.env
        run: |
          # Write the content of the secret into .env.local
          cp projects/web/.env/.env.test projects/web/.env.local

      - name: Deploy Web Main to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEB_PROD_ID }}
        run: yarn netlify deploy --prod --filter @statstrade/web
        

